### PR TITLE
fix: dark mode

### LINKED ISSUE #2: Fix dark mode
For dark mode to work we need to either create inverted/white versions of our svgs, _or_ see if we can invert the black svgs to white with css (I can't remember if css filters apply to linked svgs).

## Resolution

- [x] I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by rajat2502**
## Fixes

Fixes #2 by @zackkrida 

## Description

Fixes dark mode

## Technical details

Change the svg colors when the theme is set to dark mode

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by rajat2502** [comment]
Hey @zackkrida, can you please guide me about where I am doing wrong. This PR is still in progress.

**Comment by zackkrida** [comment]
Hi @rajat2502, you had a small typo in the css class and one incorrect value in the filter that caused your changes to not work. I fixed and merged though! Excellent work and research; I didn't think this feature was going to be possible using `filter` but you figured it out 😸

**Comment by rajat2502** [comment]
Hey @zackkrida, thanks for helping me out!!!
It's great to know that I was able to help. I am surely looking forward to contributing more to the organization. I would love to suggest more features and fix more bugs.

**Comment by rajat2502** [comment]
I was thinking if we should add a download option there as well. Let me know if it's required or will be of some help then I will be happy to work on it as well.

**Comment by rajat2502** [comment]
Another thing that came into my mind while working on this issue is that there should be an option to change the height & width of the images (just like the font size). Otherwise, some images might overflow from the `image-wrapper`.

**Comment by zackkrida** [comment]
@rajat2502 Please, make issues for any of your ideas! I already did for one of them: https://github.com/creativecommons/og-image-generator/issues/4

**Pull request merged**
