### PR TITLE
Add Vocabulary fonts

### LINKED ISSUE #11: Use correct fonts
The generated og images do not use the fonts from `vocabulary`: [Source Sans Pro and Roboto Condensed](https://cc-vocabulary.netlify.app/?path=/docs/tokens-typography--heading-title). They should be added and there should be a dropdown to choose which one is in use.

One difficulty here—the Puppeteer instance that generates the images doesn't have network access, so the woff2 files for the fonts will need to be added locally, encoded as base64, and inlined in the css. 

You can see how to do this _here_: https://github.com/vercel/og-image/blob/8026662bccaa750af4783a00e87614d1676b3b2e/api/_lib/template.ts#L10

### PR DESCRIPTION
**Pull request by krysal**
## Fixes

Fixes #11 by @zackkrida.

## Description

This PR adds the Vocabulary's fonts, Source Sans Pro and Roboto Condensed, making use of the first by default. Also adds the dropdown to choose which one to use.

## Deployment preview

See https://cc-og-image-generator.krysal.vercel.app/

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by zackkrida — CHANGES_REQUESTED** [review]
This is so great! Makes the images match the vocabulary branding so much better.

My only feedback is that when 'Roboto Condensed' is in use, it should be all-caps and bold. You can reference the styles here: https://cc-vocabulary.netlify.app/?path=/docs/tokens-typography--heading-title

Thanks!

**Comment by krysal** [comment]
Done! Thank you for the clear instructions. 👍🏻

**Review by zackkrida — APPROVED** [review]
Awesome!

**Comment by zackkrida** [comment]
side note—we can use _inline styles_ in the markdown field to use both fonts at once, like this!

https://cc-og-image.vercel.app/CC%20Global%20Summit%202020%3Cbr%20%2F%3E%3Cspan%20style%3D%22font-size%3A%20100px%3B%20font-family%3A%20Source%20Sans%20Pro%3B%20font-weight%3A%20normal%3B%20text-transform%3A%20none%3B%22%3EStarts%20in%20**20**%20days.%3C%2Fspan%3E.png?theme=light&md=1&fontFamily=roboto-condensed&fontSize=125px&images=https%3A%2F%2Fcc-vocabulary.netlify.app%2Flogos%2Fcc%2Flogomark.svg%23logomark

global-summit-example

**Pull request merged**
